#!/bin/sh

# run this ' chmod +x clean.sh '

##############################################################################
##
##  Clean workingdir script for UN*X
##
##############################################################################

rm -rf node_modules/
rm -rf public/
rm -rf .cache/

echo "cleaned"
